# Docker compose file for MediaWiki
# You probably don't want to run this file directly.
# Run `bash setup_wiki.sh` instead to set up the MediaWiki instance and see the
# README.md for more information.

services:
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_USER=mediawikiuser
      - MEDIAWIKI_DB_PASSWORD=mediawikipassword
    volumes:
      - ./Loftia:/var/www/html/skins/Loftia
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - db_data:/var/lib/mysql
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawikiuser
      - MYSQL_PASSWORD=mediawikipassword
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  db_data:

